### ISSUE TITLE
회원가입, 상세페이지 레이아웃 수정

### ISSUE THREAD

**Issue by Dev-RyanK** [Hanghae99-FinalProject-Buycation/FE-Buycation#114]
## Description
디자인 마무리에 따른 회원가입, 상세 페이지 레이아웃 수정 및 단위 통일

## Todo
- [x] 회원가입 페이지
- [x] 상세 페이지 PC
- [x] 상세 페이지 모바일
- [x] 회원가입 페이지 2차 PC
- [x] 회원가입 페이지 2차 모바일
- [x] 헤더 로고 변경 및 버튼 분기 추가
- [x] 헤더 아이콘에 cursor:pointer 추가
- [x] 상세 페이지 모바일뷰에서 사진 위 마진 추가
- [x] 헤더 로고 수정
- [x] 상세페이지 신청자 디폴트 이미지 처리
