### ISSUE TITLE
마이프로필 데이터 조회

### ISSUE THREAD

**Issue by cchloe0927** [Hanghae99-FinalProject-Buycation/FE-Buycation#120]
## Description
마이프로필 데이터 조회

## Todo
- [ ] 프로필 더미 데이터 생성
- [ ] 헤더 마이프로필 아이콘 클릭 시 통신
- [ ] 마이 프로필 데이터 조회

## Etc
기타사항
