### ISSUE TITLE
스타일 컴포넌트 자식 선택자 수정

### ISSUE THREAD

**Issue by cchloe0927** [Hanghae99-FinalProject-Buycation/FE-Buycation#122]
## Description
스타일 컴포넌트 자식 선택자 수정

## Todo
- [ ] nth-child -> nth-of-type 변경
- [ ] 자식 선택자 수정
- [ ] theme 적용시 인라인이 아닌 스타일드 컴포넌트에서 적용

## Etc
기타사항
