### ISSUE TITLE
지도 렌더링 에러 처리

### ISSUE THREAD

**Issue by cchloe0927** [Hanghae99-FinalProject-Buycation/FE-Buycation#126]
## Description
빈 배열인 경우 에러 처리

## Todo
- [ ] 옵셔널 체이닝 사용
- [ ] 중심 좌표 구하기
- [ ] 게시글 여러 마커 띄우기

## Etc
기타사항
