### ISSUE TITLE
최소단위 컴포넌트 작업(인풋, 버튼)

### ISSUE THREAD

**Issue by Dev-RyanK** [Hanghae99-FinalProject-Buycation/FE-Buycation#18]
## Description
최소단위 컴포넌트 작업(인풋, 버튼)

## Todo
- [x] 인풋 뼈대 작업
- [x] 버튼 뼈대 작업
- [x] 버튼 color 속성 추가
