### ISSUE TITLE
유저 피드백 적용

### ISSUE THREAD

**Issue by cchloe0927** [Hanghae99-FinalProject-Buycation/FE-Buycation#353]
## Description
유저 피드백 적용

## Todo
- [x] 작성 : 제목 30제한, 가격 Infinity 처리, 인원 모집 placeholder
- [x] 작성 : 예상 금액 형식(쉼표) 추가
- [x] 토큰 만료기간 1시간
- [x] 헤더 : 로그인 아이콘 변경
- [x] 유저 가이드 : 이미지 변경
- [x] 알림 : 바깥 버튼 클릭 시 모달 제거, 알림 내용 없을 때 문구 안내

- [x] 헤더 탭바 모달창 버튼 순서 변경
- [x] 알림 전체 삭제 기능 추가
- [x] 메인 공구 카드 CSS 추가
- [x] 아이폰 미니 기준 모바일 높이 fix
- [x] 프로필 빈 컨텐츠인 경우 안내 문구 처리

## Etc
기타사항
